services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-container
    ports:
      - "3000:80"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_BACKEND_URL=http://localhost:5000
    networks:
      - app_network
      
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-container
    working_dir: /app
    volumes:
      - ./backend:/app
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase
      - JWT_SECRET=test123
      - NODE_ENV=development
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - app_network

  mongo:
    image: mongo:latest
    container_name: mongo-container
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app_network

volumes:
  mongodb_data:
    driver: local

networks:
  app_network: